### PR TITLE
Move serialization decision from server to client

### LINKED ISSUE #1593: Drift 1.1.0 - Isolate Serialization
Hey, 
thanks for your awesome library!

We just migrated from moor to drift, but our isolate setup doesn't work with the newest version.
It runs fine from the main thread, but when we try to access the database from our android workmanager thread, we get the following exception.

<details>
  <summary>Exception</summary>
  
```
E/flutter (30424): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
E/flutter (30424): #0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
E/flutter (30424): #1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:230:5)
E/flutter (30424): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (30424): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (30424): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (30424): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (30424): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30424): #7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (30424): #8      _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (30424): #9      _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (30424): #10     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (30424): #11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (30424): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (30424): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (30424): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30424): #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (30424): #16     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (30424): #17     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (30424): #18     _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
E/flutter (30424): #19     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
E/flutter (30424): #20     DriftCommunication._send (package:drift/src/remote/communication.dart:117:19)
E/flutter (30424): #21     DriftCommunication.request (package:drift/src/remote/communication.dart:103:5)
E/flutter (30424): #22     _RemoteQueryExecutor.ensureOpen (package:drift/src/remote/client_impl.dart:133:10)
E/flutter (30424): #23     DatabaseConnectionUser.doWhenOpened (package:drift/src/runtime/api/connection_user.dart:154:21)
E/flutter (30424): #24     DatabaseConnectionUser.customStatement (package:drift/src/runtime/api/connection_user.dart:381:19)
E/flutter (30424): #25     setTmpDirForAndroid (package:x_code_manager/gears/services/database_provider.dart:83:12)
E/flutter (30424): <asynchronous suspension>
```
</details>

This doesn't happen when using v1.0.1, do we maybe have to adjust our database setup?

<details>
  <summary>Database setup</summary>
  
```
  Future<AppDatabase> database(String customerId) async {
    final receivePort = ReceivePort();

    final existingIsolate = IsolateNameServer.lookupPortByName(customerId);
    DriftIsolate? isolate;
    if (existingIsolate == null) {
      await Isolate.spawn(
        _startBackground,
        _IsolateStartRequest(
          receivePort.sendPort,
          _dirs.dataDir.file("$customerId.sqlite").path,
        ),
      );
      isolate = await receivePort.first as DriftIsolate?;
      if (isolate != null) {
        IsolateNameServer.registerPortWithName(isolate.connectPort, customerId);
      }
    } else {
      isolate = DriftIsolate.fromConnectPort(existingIsolate);
    }

    final connection = await isolate!.connect();

    final db = AppDatabase.connect(connection);

    setTmpDirForAndroid(db);
    return db;
  }
}

void _startBackground(_IsolateStartRequest request) {
  final executor = NativeDatabase(
    File(request.targetPath),
    setup: (database) {
      //some custom functions ...
    },
  );
  final moorIsolate = DriftIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
}
```

</details>

Thank you for any advice!

### PR DESCRIPTION
**Pull request by kuhnroyal**
Enable the `DriftServer` to handle connections from clients independent of their serialization configuration.

Fixes #1593

### CODE REVIEW

File: drift/lib/isolate.dart [hunk 1]
```diff
@@ -39,13 +39,17 @@ class DriftIsolate {
...
   final SendPort connectPort;
 
+  /// The flag indicating whether messages between this [DriftIsolate]
+  /// and the [DriftServer] should be serialized.
+  final bool serialize;
+
   /// Creates a [DriftIsolate] talking to another isolate by using the
   /// [connectPort].
-  DriftIsolate.fromConnectPort(this.connectPort);
+  DriftIsolate.fromConnectPort(this.connectPort, {this.serialize = true});
```
Comment (simolus3) [inline drift/lib/isolate.dart:48]: Could you also add the `{@macro drift_isolate_serialize}` macro to the docs on this constructor?

**Review by simolus3 — COMMENTED** [review]
Nice, thank you :+1:

File: drift/lib/isolate.dart (hunk 1 above)
Comment (kuhnroyal) [reply drift/lib/isolate.dart:64]: I moved the template here and removed it from `connect` and `shutdown`

**Comment by simolus3** [comment]
Thanks!
